### ISSUE TITLE
define module-name prefixing rules

### ISSUE THREAD

**Issue by kwatsen** [netconf-wg/restconf#14]
The draft defines "api-identifier" in section 2.5.1.1 (ABNF For Data Resource Identifiers) as follows:

    api-identifier = [module-name ":"] identifier

but, AFAICT, it is never defined that the module-name MUST prefix the identifier if and only if the identifier comes from a different module than the previous identifier in the URL path.

**Comment by abierman** [comment]
Resolution: JSON rule will be SHOULD use prefix. RESTCONF will follow this guideline

**Comment by abierman** [comment]
resolved in -04 release
