### ISSUE TITLE
Contradicition between chapter 6.3 example and ietf-restconf-monitoring module

### ISSUE THREAD

**Issue by manoe** [netconf-wg/restconf#23]
Hi,

In chapter 6.3 the example is the following:
```
GET /restconf/data/ietf-restconf-monitoring:restconf-state/streams/stream=NETCONF/encoding=xml/location HTTP/1.1
Host: example.com
Accept: application/yang.data+xml
```
While the ietf-restconf-module has a path to the location leaf:
```
restconf-state/streams/stream/access/location
```
The `encoding` leaf is on the same level as the `location` leaf. Moreover, for the `access` list, the `type` leaf is defined as the key, however there is no `type` among the list elements.

I would propose to change the ietf-restconf-monitoring module's access list the following way:
```
list access {
  key encoding;
  min-elements 1;
  ...etc...
```
And update the example in chapter 6.3:
```
GET /restconf/data/ietf-restconf-monitoring:restconf-state/streams/stream=NETCONF/access=xml/location HTTP/1.1
Host: example.com
Accept: application/yang.data+xml
```

Br,
-Balint Uveges

**Comment by abierman** [comment]
Fixed this issue in github.
Cannot release -06 version because oxtradoc is not
generating XML that is compatible with the xml2rfc
that Ubuntu 14.04 installs.  The Ubuntu 12.04 version
says it works but no TXT file is produced

**Comment by abierman** [comment]
Found another linux PC to generate doc OK; draft-06 released with fix
for this issue and corrected JSON Metadata reference

**Comment by manoe** [comment]
Hi, draft-ietf-netconf-restconf-06 looks fine for me. Should I close the issue?
