### ISSUE TITLE
add another URL encoding example to the Section 3.5.1

### ISSUE THREAD

**Issue by kwatsen** [netconf-wg/restconf#28]
What would the URI look like if the key value contained the following characters: comma, single-quote, double-quote, colon, slash, space ?
 
[KENT] We should add an example to the text that covers a case like this.  Right now the only example regards how to encode a multi-key list without any URL escapes...
 
[NICK] Thanks, that would be really helpful.

**Comment by abierman** [comment]
added -- see issue #27

**Comment by abierman** [comment]
closed in restconf-09
