### ISSUE TITLE
3.6 action shown with a <data-resource-identifier>

### ISSUE THREAD

**Issue by abierman** [netconf-wg/restconf#34]
An action is invoked as:

   POST {+restconf}/data/<data-resource-identifier>/<operation>
   where <data-resource-identifier> contains the path to the data node
   where the action is defined, and <operation> is the name of the
   action.

data-resource-identifier was removed and no longer exists

**Comment by mbj4668** [comment]
The term is just used in this paragraph.  Is that a problem?   We could have said:
     POST {+restconf}/data/<foo>/<operation>
    where <foo> is ... and <operation> is ...

**Comment by abierman** [comment]
The term is not defined anywhere. There is no specification of data-resource-identifier
so it should just be plain text instead here.

**Comment by mbj4668** [comment]
It is not a term, it is just a "variable name" , and it is explained in the same paragraph:
```
   where <data-resource-identifier> contains the path to the data node
```
This is just like it is done in a few other places in the document.

**Comment by abierman** [comment]
OK - I hope the syntax of 'path' is clear
