### ISSUE TITLE
dicuss of the policy for  multiple version YANG

### ISSUE THREAD

**Issue by cyqw** [netconf-wg/restconf#35]
The YANG file may have multiple version, if we have two version YANG in system, and we should support both. Is it possible in restconf for support multiple version YANG?

**Comment by abierman** [comment]
For YANG 1.0 modules it is not defined whether this is allowed.
For YANG 1.1 modules, this is not allowed.
RESTCONF follows the rules in YANG, just like NETCONF

**Comment by abierman** [comment]
not a RESTCONF issue
