### ISSUE TITLE
TP review of restconf-09

### ISSUE THREAD

**Issue by abierman** [netconf-wg/restconf#45]
From Tom Petch

https://www.ietf.org/mail-archive/web/netconf/current/msg10888.html

**Comment by abierman** [comment]
- removed text about knowledge of NETCONF needed
 - moved terminology section before old 1.1
- OPEN ISSUE: change term 'state data' to 'operational data'
- clarified intro text wrt/ interactions with NETCONF and access to specific datastores
- did not change XML 1.0 reference from 2008 ver to 2001 ver
- did not change candidate text to MUST; implies the operation cannot fail, which is not true
- clarified RPC operation term

-OPEN ISSUE

s.2.2 "Consistent with the exclusive use of X.509v3 certificates for
NETCONF over TLS [RFC7589],  use of certificates in RESTCONF is also
limited to X.509v3 certificates."

I think that this is open to misinterpretation.  It is the use of TLS by
NETCONF that is limited to X.509v3 certificates, not that when TLS uses
certificates, as opposed to e.g. PSK, then they must be X.509v3.  I seem
to recall the IESG getting this wrong with call-home so best to be
precise.

 - changed authenticated to authorized
- added top-level data node to YANG terms

- OPEN ISSUE: did not add rockandroll .well-known example to show it can be different

- OPEN ISSUE: rename 'operation' to 'operations


s.3.2 In a similar vein, a media type of  'application/yang.errors+xml '
corresponds to a resource of 'errors', just what I would expect, until a
media type of 'application/yang.operation+xml ' corresponds to
'operations'.  Another fruitful source of coding errors:-)


- did not rename nonconfig to something else.
- Clarified server implementation requirements for YANG defaults
- Clarified optional YANG retrieval vs. mandatory library retrieval

**Comment by abierman** [comment]
OPEN: term: consider operational state; no changes yet; reusing NETCONF term state data;
check if used consistently

OPEN s2.2: we think the RFC reference is clear; no change

OPEN well-known. : not adding new example; refer to the .well-known RFC

OPEN: operations -- no change ; matches operation; not the container called operations

**Comment by abierman** [comment]
- added RESTCONF Ext. section
- fixed sec 3.4

**Comment by abierman** [comment]
TLS issues left for Kent

**Comment by kwatsen** [comment]
I fixed s.2.2   - K.

**Comment by abierman** [comment]
OPEN well-known. : not adding new example; refer to the .well-known RFC

Added example for /top/restconf

**Comment by abierman** [comment]
closed in draft-10
