### ISSUE TITLE
sec. 4.8.1: content parameter default for datastore

### ISSUE THREAD

**Issue by abierman** [netconf-wg/restconf#50]
The content query parameter gets its default value from
the config-stmt of the data node. (Will be rewritten in -10
to be less confusing)

The config param is also allowed for the datastore and that has no config-stmt.

What is the default?

Consider interaction with fields:

  GET /restconf/data?fields=system;restconf-state;interfaces

If the default is config then the nonconfig fields selected will get skipped.
If the the default is nonconfig then the config fields selected will get skipped.

The default needs to be 'all' for the datastore resource type

**Comment by mbj4668** [comment]
What is "The config param"?  I don't understand the issue here...

However, is the design with the "content" param future-proof?  What if an "ephemeral" datastore is added, can it be handled by extending the "content" param?  Can RESTCONF extentions add query params?

**Comment by abierman** [comment]
If the target resource identifies a datastore resource,
then the default value is "all".
If the target resource identifies a data resource,
then the default value is determined by the "config" statement value of the

**Comment by abierman** [comment]
closed in draft-10
