### ISSUE TITLE
JSON encoding of empty containers

### ISSUE THREAD

**Issue by abierman** [netconf-wg/restconf#54]
From Robert Wilton:

2. The "D.1.1.  Retrieve the Top-level API Resource" example looked slightly wrong to me.  from the  RESTCONF module definition in section 8 I would expect the data and operations container to be empty JSON objects.

OLD:
   The server might respond as follows:

      HTTP/1.1 200 OK
      Date: Mon, 23 Apr 2012 17:01:00 GMT
      Server: example-server
      Content-Type: application/yang.api+json

      {
        "ietf-restconf:restconf": {
          "data" : [ null ],
          "operations" : [ null ]
        }
      }
 
NEW:
   The server might respond as follows:

      HTTP/1.1 200 OK
      Date: Mon, 23 Apr 2012 17:01:00 GMT
      Server: example-server
      Content-Type: application/yang.api+json

      {
        "ietf-restconf:restconf": {
          "data" : { },
          "operations" : { }
        }
      }

**Comment by abierman** [comment]
We will ask Lada and check the YANG-JSON draft.
That is the normative text for this issue

**Comment by llhotka** [comment]
I tend to agree with Rob. [draft-ietf-netmod-yang-json](https://tools.ietf.org/html/draft-ietf-netmod-yang-json) defines `[null]` as the encoding of leafs with *empty* type, and nothing else. So using empty objects is IMO a better indication that some suppressed contents are inside.

**Comment by mbj4668** [comment]
In fact, I think all occurences of [null] should be replaced with {}

**Comment by abierman** [comment]
This should not be changed because the JSON draft says an empty leaf is NULL

**Comment by llhotka** [comment]
IMO, the yang-json draft gives you no guideline, because the terms *leaf* and *empty* are meant in the narrow sense, i.e. a leaf node and and empty type, as defined in YANG. What you have here are some containers whose contents are omitted. So I think you can choose whatever makes most sense.
