### ISSUE TITLE
How does a RESTCONF server indicate which ietf-yang-library revision is implemented

### ISSUE THREAD

**Issue by abierman** [netconf-wg/restconf#55]
The ietf-yang-library contains a /modules subtree.
A RESTCONF client needs to read the /modules subtree
in order to find out which revision of the module is implemented.

Some mechanism is needed to tell the client which revision is implemented

**Comment by abierman** [comment]
Propose that a new mandatory capability URI is added indicating the module revision

**Comment by mbj4668** [comment]
But the capabilities are reported in ietf-restconf-monitoring, so now the question becomes which version of ietf-restconf-monitoring does the server support?  Can we say that restconf version 1 implies a certain revision of ietf-restconf-monitoring?  Or would it be better to move the capabilities list to the API resource?

**Comment by abierman** [comment]
I will have to remove the yang-library capabilities.
Maybe the capabilities should be in /restconf/capabilities
instead of /restconf/data.

Otherwise RESTCONF-1 has to hard-wire the expected revision

**Comment by mbj4668** [comment]
RIght, put them in the API resource under /restconf/capabilites, i,e, in the 'restconf' grouping in ietf-restconf.yang

**Comment by abierman** [comment]
I think this is too disruptive and leaves only /restconf-state/streams

What about just adding a leaf with the revision data

  /restconf/yang-library-revision

 contains a revision-date string

**Comment by abierman** [comment]
closed in draft-10; example fixed in draft-11
