### ISSUE TITLE
restconf error code bug

### ISSUE THREAD

**Issue by abierman** [netconf-wg/restconf#61]
Hi,

The RESTCONF draft lists a mapping from NETCONF error tags to HTTP
error codes.  It maps "too-big" to "413".  But this is not entirely
correct.  "too-big" is used when either the request is too large or the
response would be too large.  413 is only used when the request is too
large.

It is not entirely clear which HTTP error code is appropriate when the
response would be too large.  403 seems to be recommended.  Maybe we
should check with the HTTP WG.

**Comment by abierman** [comment]
not obvious, but could return 400 Bad Request

**Comment by abierman** [comment]
settle on 400

**Comment by kwatsen** [comment]
server returns 413 when request too large, and 400 when generated response is too large

**Comment by abierman** [comment]
fixed

**Comment by abierman** [comment]
fixed in draft-15
